include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking
  - webgl-demo

build doc:
  stage: build
  only:
    - /^v.*/
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip
  - doxygen Documentation/Autogen/Doxyfile
  - mv Documentation/Autogen/html/ docs/
  - cd docs/ && zip -r ../build.zip *
  artifacts:
    paths:
    - build.zip

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unity-store

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []

build-webgl-demo:
  stage: webgl-demo
  image: unityci/editor:2019.4.27f1-webgl-0.13.0
  script:
    - chmod +x ./cicd/build-webgl-demo.sh && ./cicd/build-webgl-demo.sh
    - mkdir -p webgl/build
    - mv Builds/WebGL/* webgl/build/
  after_script:
    - mkdir -p webgl/logs/
    - mv Logs/* webgl/logs/
  artifacts:
    when: always
    paths:
      - webgl