include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking
  - code-analysis
  - autotests
  - package-export
  - build-demo-2019
  - build-demo-2020
  - build-demo-2021

variables:
  PROJECT_PATH: "%cd%"
  AUTOTESTS_BAT: "cicd/autotests.bat"
  PACKAGE_BAT: "cicd/package-export.bat"
  PACKAGE_NAME: xsolla-commerce-sdk.unitypackage
  BUILD_ROOT_PATH: "Builds"
  BUILD_SCRIPT: "./cicd/build-universal.sh"
  BUILD_BAT: "cicd/build-universal.bat"
  BUILD_TARGET_WINDOWS: "StandaloneWindows64"
  BUILD_TARGET_WEBGL: "WebGL"
  BUILD_TARGET_ANDROID: "Android"
  UNITY_2019_VERSION: "2019.4.27f1"
  UNITY_2020_VERSION: "2020.3.14f1"
  UNITY_2021_VERSION: "2021.1.13f1"
  BUILD_PLATFORM: "window"
  GIT_CLEAN_FLAGS: -ffdx

build doc:
  stage: build
  only:
    - /^v.*/
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip
  - doxygen Documentation/Autogen/Doxyfile
  - mv Documentation/Autogen/html/ docs/
  - cd docs/ && zip -r ../build.zip *
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unity-store
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  tags:
    - sshclient
  dependencies: []

analyze-code:
  stage: code-analysis
  allow_failure: true
  script:
    - call cicd\code-analysis.bat
  artifacts:
    name: "SDK_analyze_code_logs_%CI_COMMIT_REF_NAME%"
    when: on_failure
    paths:
      - Logs
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# AUTOTESTS

run_autotests:
  stage: autotests
  script:
    - call %AUTOTESTS_BAT% %PROJECT_PATH% %UNITY_2019_VERSION%
  artifacts:
    name: "AUTOTESTS_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Logs/autotest_results.txt
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows
    
# =================================================================================================================
# PACKAGE EXPORT

export_package:
  stage: package-export
  script:
    - call %PACKAGE_BAT% %PROJECT_PATH% %UNITY_2019_VERSION% %PACKAGE_NAME% %BUILD_ROOT_PATH%
  artifacts:
    name: "PACKAGE_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Logs/export_results.txt
      - Logs/create_results.txt
      - Logs/import_results.txt
      - Logs/xsolla-commerce-sdk.unitypackage
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2019

build-windows-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2019:
  stage: build-demo-2019
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2019_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2019_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2019_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2020

build-windows-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2020:
  stage: build-demo-2020
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2020_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2020_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2020_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

# =================================================================================================================
# UNITY 2021

build-windows-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WINDOWS% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_WINDOWS%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WINDOWS%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-webgl-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_WEBGL% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_WEBGL%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_WEBGL%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows

build-android-2021:
  stage: build-demo-2021
  script:
    - call %BUILD_BAT% %PROJECT_PATH% %UNITY_2021_VERSION% %BUILD_ROOT_PATH% %BUILD_TARGET_ANDROID% %BUILD_PLATFORM%
  artifacts:
    name: "%UNITY_2021_VERSION%_%BUILD_TARGET_ANDROID%_%CI_COMMIT_REF_NAME%"
    when: always
    paths:
      - Builds/%BUILD_TARGET_ANDROID%-%UNITY_2021_VERSION%
    expire_in: 3 days
  dependencies: []
  tags:
    - sdk_ci
    - windows
